
[package]
name = "captcha"
version = "0.1.0"
edition = "2021"
authors = ["panglijun <819820211@qq.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
image = "0.24"
base64 = "0.21"
imageproc= "0.23"
rusttype = "0.9"
